[options]
db_host = False
db_port = False
db_user = suraj
db_password = False
addons_path = /Users/suraj/Desktop/8848 connect/odoo/addons,/Users/suraj/Desktop/8848 connect/8848-connect-addons
admin_passwd = $pbkdf2-sha512$600000$3Xuvde49xxgDYOx9713rnQ$tUFGhUl7hAgarEljxM0duPhBdv4VjiaY7YS7RZR.s8487jOo4PX6lknxLdOmknsCAWWIvq9/pPVB9yyrTfMg/w

