{
    'name': '8848 Connect - Baseline Tests',
    'version': '1.0',
    'category': 'Hidden/Tests',
    'summary': 'Milestone 0 regression suite; installing this module on an '
               'empty database is the full-stack install test.',
    'author': '8848 Momo House',
    'depends': [
        '8848_core_branding',
        '8848_glass_skin',
        '8848_dashboard',
        '8848_franchise',
        '8848_royalty',
        '8848_marketing_fee',
        '8848_store_performance',
        '8848_factory',
        '8848_inventory',
        '8848_warehouse',
        '8848_quality',
        '8848_delivery',
        '8848_driver',
        '8848_portal',
        '8848_supplier',
        'sign_oca',
        'theme_liquid_glass',
    ],
    'data': [],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
