{
    'author': '8848 Momo House',
    'name': '8848 Connect - Franchise Portal',
    'version': '1.0',
    'category': 'Website/Portal',
    'summary': 'Dedicated web portal for Franchisees to view deliveries and royalties.',
    'depends': ['portal', 'website', '8848_franchise', '8848_royalty'],
    'data': [
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        'wizard/portal_invite_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/portal_templates.xml',
        'views/order_templates.xml',
        'views/delivery_templates.xml',
        'views/finance_templates.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
