{
    'name': '8848 Connect - Delivery Routes',
    'version': '1.0',
    'category': 'Operations/Delivery',
    'summary': 'Phase 4: 8848_delivery',
    'author': '8848 Momo House',
    'depends': ['stock', 'hr', 'fleet', '8848_security', '8848_communication'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/delivery_stage_data.xml',
        'reports/report_packing_slip.xml',
        'reports/report_delivery_slip.xml',
        'data/ir_sequence_data.xml',
        'views/delivery_route_views.xml',
        'views/stock_picking_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
